spring.application.name=alocamara
spring.datasource.url=jdbc:postgresql://db.SEU_PROJECT_ID.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=SUA_SENHA
spring.jpa.hibernate.ddl-auto=validate
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://SEU_PROJECT_ID.supabase.co/auth/v1/.well-known/jwks.json